# Generated by Django 4.1.7 on 2023-03-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_admin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text="<i></i> tagining class atributi uchun qo'yiladigan class nomi", max_length=300),
        ),
    ]
