# Generated by Django 4.1.7 on 2023-03-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
