# Generated by Django 4.1.7 on 2023-03-13 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_service_icon_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='blog.admin'),
        ),
    ]
