# Generated by Django 4.1.7 on 2023-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_sociallink_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='field',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
