# Generated by Django 4.1.7 on 2023-03-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_created_comment_updated_reply_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content',
            new_name='content_reply',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='full_name',
            new_name='full_name_reply',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='image',
            new_name='image_reply',
        ),
    ]
