# Generated by Django 4.1.7 on 2023-03-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_content_reply_content_reply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='comment_id',
        ),
    ]
