# Generated by Django 4.1.7 on 2023-03-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_comment_reply_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='email_feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='field',
            new_name='field_feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='full_name',
            new_name='full_name_feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='image',
            new_name='image_feedback',
        ),
    ]
